<?php


class EModeratore extends EUtente
{
    private $id;

    /**
     * @param $id
     */
    public function __construct($id=null)
    {
        $this->id = $id;
    }


    public function banUtente(EUtente $utente, Date $tempo_ban){

    }

    public function cancellaRicetta(ERicetta $ricetta)
    {
        parent::cancellaRicetta($ricetta); // TODO: Change the autogenerated stub


    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }
}